name: Backend PR Test

on:
  push:

jobs:
  keycloak-build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: github-actions-test
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '13' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
      - name: check classpath
        run: |
            echo %CLASSPATH%
            echo %PATH%
      - name: Translation check
        run: java main.resources.TranslationCheck